### ISSUE TITLE
Why is access to the user's home necessary?

### ISSUE THREAD

**Issue by Newbytee** [flathub/io.openrct2.OpenRCT2#14]
According to the comment in the manifest https://github.com/flathub/io.openrct2.OpenRCT2/blob/master/io.openrct2.OpenRCT2.yaml#L16 this is used for getting access to the game files, but OpenRCT2 seems to use xdg-desktop-portal, so why is this necessary?

**Comment by takluyver** [comment]
It's possible no-one ever put all the bits together. I did some work on Flatpak-ing OpenRCT2, but I didn't look into how it was actually displaying the file selection dialog. It looks like it uses Zenity or KDialog in a subprocess, Zenity uses GtkFileChooserNative if built with GTK >= 3.20, and GtkFileChooserNative uses the portal. So as long as the `org.freedesktop.Platform` 20.04 runtime contains Zenity & a recent GTK, it should work without home access.

If you manually disable home access (e.g. using [Flatseal](https://github.com/tchx84/Flatseal)), can you still select the game data files under your home directory? And is it still able to access the same files after closing and reopening the app? And after restarting your computer?

**Comment by Newbytee** [comment]
> If you manually disable home access (e.g. using [Flatseal](https://github.com/tchx84/Flatseal)), can you still select the game data files under your home directory? And is it still able to access the same files after closing and reopening the app? And after restarting your computer?

I haven't tried this yet, however I was able to access my RollerCoaster 2 & 1 installations that are mounted outside my home (at `/mnt/storage`). I'll give it a shot though.

**Comment by rmnvgr** [comment]
I think it’s also needed for opening scenarios and saved games from the file manager, and maybe choosing RCT1 installation folder in-game. I’m unable to test it for a few days, I’ll check it next week.

**Comment by rmnvgr** [comment]
I've been able to add the data directories from RCT1 & 2 and open save files with the permission removed, and it still worked after a restart. However it greatly increased the game and park loading times.

Maybe we can try to drop the permission for the beta builds, and see if any issue arises before dropping it for the stable builds?

**Comment by takluyver** [comment]
That speed difference might be of interest to the Flatpak developers. I think that accessing files through the portal (without the filesystem permissions) uses a FUSE mount - I'd guess that's what affects the speed. Do you know what sort of access pattern it uses? E.g. are there lots of small reads? Or does it mmap the files?

**Comment by Newbytee** [comment]
> However it greatly increased the game and park loading times

I've noticed this as well. I was actually wondering why those were so slow, but this explains it. My RCT 1 & 2 installations are outside of my home directory, so it makes sense they would be affected even without the permission removed.

**Comment by rmnvgr** [comment]
I've remove the filesystem permission in the `beta` branch, and the loading times seem normal there. Maybe the code has been optimized since the latest release.

If we get no reports of issues from users, I suggest we remove the filesystem permission on the stable builds for the next OpenRCT2 release.

**Comment by Newbytee** [comment]
The loading times still feel kind of slow for me, but definitely faster than on stable. That said I haven't tested a non-Flatpak build so I'm not sure how fast they usually are, and I'd say these loading times are acceptable.

**Comment by rmnvgr** [comment]
The filesystem permission is now removed in the `master` branch.
