### ISSUE TITLE
Build with SDL 2

### ISSUE THREAD

**Issue by takluyver** [flathub/io.openrct2.OpenRCT2#2]
My mistake, I didn't read the instructions carefully enough at first, and it seemed to work with SDL 1.2. @rmnvgr, do you have time to try this? We'll need to update SDL_ttf as well, I think.

https://github.com/flathub/io.openrct2.OpenRCT2/blob/d92ff642e6118cb1d462a12300fe97a11983b75f/io.openrct2.OpenRCT2.yaml#L25-L26

**Comment by janisozaur** [comment]
Sdl_ttf is not used

**Comment by takluyver** [comment]
Thanks! I had got that from the instructions here: http://openrct2.org/quickstart/install/linux/fedora

**Comment by takluyver** [comment]
And it turns out that the base image already contains SDL 2, so these were just unnecessary.

**Comment by takluyver** [comment]
OK, could someone test #3:

```
flatpak install --user https://dl.flathub.org/build-repo/24538/io.openrct2.OpenRCT2.flatpakref
```

I'm not expecting this to improve anything, I just want to verify that nothing has broken.
