### ISSUE TITLE
Discord (Flatpak) Rich Presence support?

### ISSUE THREAD

**Issue by rlad78** [flathub/io.openrct2.OpenRCT2#20]
Firstly, thank you all for bringing OpenRCT2 in the form of a Flatpak. I've been running OpenRCT2 on different Linux distros just fine using the normal installation method, but something went haywire on my openSUSE build and nothing I did would resolve the issue. Flatpak to the rescue 🙏

Is it possible that Discord RP can be added? Short instructions from the Discord Flatpak maintainers can be found [here](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)#flatpak-applications). They suggest the following:

> 1. Add `--filesystem=xdg-run/app/com.discordapp.Discord:create` to `finish-args`
> 2. Create a wrapper (if you don't already have one) for the apps binary and add something like this 
> ```sh
> for i in {0..9}; do
>     test -S $XDG_RUNTIME_DIR/discord-ipc-$i || ln -sf {app/com.discordapp.Discord,$XDG_RUNTIME_DIR}/discord-ipc-$i;
> done
> ```

**Comment by rmnvgr** [comment]
Thank you for your support!

I had looked at adding support to Discord RPC in the past, without success.

I'll try to look a it again, last time I checked, as mentioned on [the OpenRCT2 wiki](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux), it required patching one of its dependencies. That plus adding a wrapper increases the maintenance burden, so I can't promise anything.

**Comment by rlad78** [comment]
Thank you for trying. I hadn't ever seen that note in the wiki, makes sense given the issues with rapidjson. It looks like the [discord-rpc](https://github.com/discord/discord-rpc) project has been discontinued due to the introduction of Linux support for [Discord Game SDK](https://discord.com/developers/docs/game-sdk/sdk-starter-guide), which looks...a lot more involved.

No worries on this though. I originally thought this would be a simple endevour, but it looks like a lot more work compared to the value of what it would accomplish.

**Comment by rmnvgr** [comment]
Let's keep this open, as it would still be nice to have.

Regarding the Game SDK, [according to the OpenRCT2 team](https://github.com/OpenRCT2/OpenRCT2/issues/11380), it's license is incompatible with the GPL, so that would be another hurdle.
