### ISSUE TITLE
File browser does not show home directory

### ISSUE THREAD

**Issue by FischOderAal** [flathub/io.openrct2.OpenRCT2#21]
Hello everyone,

I anstalled OpenRCT2 via the popShop (I'm on popOS! 20.04 LTS) and when I opened it I could not add the externally installed RCT2. When I went to my home directory it did not show any files. RCT2 was installed from GOG via Heroic Launcher.

I proceeded to then download the installer from GOG and the OpenRCT2 dialogue to install it. The files in the Download folder were all visible.

When I now want to add the RCT1 files (installed via Heroic Launcher from GOG) from within the game, I cannot choose the files as the home folder is empty (again). When I click on the Desktop nothing happens.

Is this an issue due to the sandboxing?

**Comment by rmnvgr** [comment]
Hello,

Flatpak uses portals to access the filesystem. Have you installed the necessary portal for your desktop environment? I'm not familiar with PopOS, so you may have to ask in their support forums how to check for that.

**Comment by FischOderAal** [comment]
Everything was correctly installed but it was due to the sandboxing. OpenRCT2 did not get access to the home folder by default. I had to install Flatseal to give it permission and now it works. Thank you for the support!

**Comment by rmnvgr** [comment]
Well, you're not supposed to give it additional permissions. On my system, OpenRCT2 doesn't have filesystem access, yet I still can add the game files through the portal.

Unfortunately, PopOS 20.04 doesn't appear to be available for download anymore, and on 22.04, the portal works as expected. So I can't tell if there's an issue with PopOS 20.04 or if your system is misconfigured.

**Comment by FischOderAal** [comment]
Whatever the reason was. For other Flatpak programs like Freecad the permissions are set correctly automatically.
