### ISSUE TITLE
Develop build fails

### ISSUE THREAD

**Issue by rmnvgr** [flathub/io.openrct2.OpenRCT2#22]
The build for the `develop` branch has been failing for two weeks (just noticed now), after this commit: https://github.com/OpenRCT2/OpenRCT2/commit/766571ba2c5cb94f87775357b6775fca2c8a6fd4

That's the error:

```
/run/build/OpenRCT2/src/openrct2/drawing/Drawing.String.cpp: In function ‘void ttf_process_string_literal(rct_drawpixelinfo*, std::string_view, text_draw_info*)’:
/run/build/OpenRCT2/src/openrct2/drawing/Drawing.String.cpp:839:66: error: ‘*(long unsigned int*)((char*)&ttfRunIndex + offsetof(std::optional<long unsigned int>,std::optional<long unsigned int>::<unnamed>.std::_Optional_base<long unsigned int, true, true>::<unnamed>))’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  839 |                     auto len = it.GetIndex() - ttfRunIndex.value();
```

The full logs are here: https://flathub.org/builds/#/builders/12/builds/10987/steps/6/logs/stdio

@Gymnasiast Do you have any idea what could be happening?

**Comment by rmnvgr** [comment]
I got it to build again somehow by resetting the CXX flags. It appears the build fails when the `-O2` flag is present.

**Comment by Gymnasiast** [comment]
This appears to be a bug in GCC. @janisozaur has created a bug report with GCC: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105937

**Comment by rmnvgr** [comment]
Thank you for the notice! I’ll watch these issues.

**Comment by janisozaur** [comment]
Fixed in GCC and OpenRCT2
