### ISSUE TITLE
Trying to run from Flatpak exits after trying to install from downloaded GOG installer. 

### ISSUE THREAD

**Issue by pwhite1989** [flathub/io.openrct2.OpenRCT2#27]
For more information, I bought the windows exe on gog -> I selected the installer -> a dialogue box pops up with the message saying it may take a few minutes -> I click ok and the dialogue box disappears, and nothing happens.

This is what I get from running `flatpak run io.openrct2.OpenRCT2`:

```shell
$ ~ flatpak run io.openrct2.OpenRCT2
Importing legacy shortcuts...
Gtk-Message: 17:03:16.128: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:03:16.128: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:03:20.846: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:03:20.847: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:03:25.198: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:03:25.198: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:03:26.204: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:03:26.205: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:03:29.689: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:03:29.689: Failed to load module "canberra-gtk-module"
$ ~
```

I am running on Arch: `Kernel: 5.18.3-arch1-1`

**Comment by rmnvgr** [comment]
Thank you for your report!

It's strange there's no other logs and it's failing silently.

I'll need to further investigate this but I won't have much free time in the coming days, so in the meantime you can manually install RCT2 using this command:

```
flatpak run --command=innoextract --filesystem=host io.openrct2.OpenRCT2 /path/to/your/installer.exe
```

And then you'll be able to select the installed files at OpenRCT2 startup.

Sorry for the inconvenience!

**Comment by pwhite1989** [comment]
No need to apologise at all! THank you for all your hard work on this.

`flatpak run --command=innoextract --filesystem=host io.openrct2.OpenRCT2 /path/to/your/installer.exe` worked excellently so thank you for that, really nice stuff.

I can close this if you want.
Cheers

**Comment by rmnvgr** [comment]
That's nice to hear!

I'll keep this open until I find what's not working.

**Comment by Gymnasiast** [comment]
This is a bug in the v0.4.0 release. It has been fixed in `develop`.

**Comment by rmnvgr** [comment]
@pwhite1989 This should be fixed in the latest update, is it possible for you to test that?
