### ISSUE TITLE
Provide nightly builds

### ISSUE THREAD

**Issue by rmnvgr** [flathub/io.openrct2.OpenRCT2#4]
Following [this discussion](https://github.com/flathub/flathub/pull/1694#issuecomment-674849314), let's discuss how best provide nightly builds of OpenRCT2 through flatpaks.

1. **Hack the beta channel** by pushing a commit every day to have it rebuild with the latest `develop` branch, however well that's a hack, and that means the user, after enabling the `flathub-beta` repo, will also be shown beta versions of every other Flathub applications in its software boutique.
2. **Package the [OpenRCT2 Launcher](https://github.com/LRFLEW/OpenRCT2Launcher/releases)** that provides prebuilt binaries, but the user will lose desktop integration (mainly opening savegames and scenarios by clicking on them in its file browser) and there's some work needed to flatpak it (no desktop file, no appstream data, no ready-to-package icon, adding the Qt 5 dependency).
3. **Provide the nightly flatpaks through the OpenRCT2 website**. As far as I can tell, it wouldn't need to host a runtime as it can be pulled from Flathub. I had a look around and that's what [Citra](https://flatpak.citra-emu.org/) is doing for their nightly builds. However I don't have any experience with flatpak repositories, and [the documentation](https://docs.flatpak.org/en/latest/hosting-a-repository.html) doesn't seem very helpful.

I would have a preference for number 3, because it's the cleanest, but if it is impossible due to infrastructure/knowledge issues, I'd say number 2 is a good workaround.

**Comment by takluyver** [comment]
The OpenRCT people were saying that they advise users in general to use the development branch, not just users who want to help test new changes while they're stabilising. I don't know if that's meant to be the case forever, or if it's a young project at the moment and more people will use the releases as it matures. Who are the releases for, if everyone should get the development branch?

This is a bit of a disconnect with Flathub, which is [pretty clear](https://github.com/flathub/flathub/wiki/App-Requirements#stable-releases-reproducible-builds) that it wants released versions, at least for the stable branch.

Maybe we could find some compromise like OpenRCT automatically tagging a weekly micro-release, which we can build a Flatpak from, so we're close to the latest changes but not giving users an update every single day.

**Comment by rmnvgr** [comment]
So if I understand correctly, you're suggesting to send weekly development builds on the stable channel? I'm not sure I'm comfortable with that, releases are here for a reason after all.

From https://openrct2.org/downloads (emphasis mine):
> OpenRCT2 has frequent stable releases. However, it is also possible to download **unstable development builds** and playtest the latest features and changes.

And from https://openrct2.io/getting-started/index.html Windows section (emphasis mine):
> The latest release is a stable, well-tested build, but may have fewer features than the latest development builds. **The dev builds are analogous to beta versions** - they should work, but don't expect everything to be perfect.

---

From the same page, I believe this is the reason why downloading the dev build would be preferable in some cases:
> Note: If you wish to play online, it is recommended to use the latest development build, as most servers will be running this; you cannot connect to a server running a different version.

I must say I always used tagged releases because I never played online. As of writing this, only a few servers use the latest dev build (server version 0.3.0-1), but as the [latest server version bump is only a few hours old](https://github.com/OpenRCT2/OpenRCT2/pulls?q=is%3Amerged+label%3A%22network+version%22+), that's hard to tell how much are running a stable or a nightly build.

Anyway, providing nightly builds in a timely manner for this use case seems important.

---

I had another look at building a flatpak repository, it turns out it's very easy: we only need to use `flatpak-builder` with the `--repo` and `--gpg-sign` options to build and sign the repository, host the generated repo somewhere, and write a `.flatpakref` file that points to this repo. Users would only need to download this file once to install the nightly build and flatpak will take care of updating them.

However I don't know anything about OpenRCT2 build system so I don't know how easy/hard it could be to do that.

**Comment by takluyver** [comment]
Aha, that's the detail I had missed: the dev version is recommended specifically for online play. Like you, I'm more interested in single player. In that case, I think the builds we post as stable on Flatpak should keep following proper releases.

The bit I'm never sure about with setting up a separate Flatpak repo is this [in the docs](https://docs.flatpak.org/en/latest/hosting-a-repository.html):

> it is important to enable HTTP keep-alive on the web server that is hosting your repository.

I don't know whether keep-alive is commonly enabled for static file hosts - things like Github pages. If it is, then there are probably free/cheap options you can use to host a repo (you might get dinged for actually putting it on Github pages, but...). If you have to run your own server, that's a rather more expensive proposition.

**Comment by rmnvgr** [comment]
I checked on a GitHub hosted website, and the connection is only closed when using HTTP1.0. I don't know which version of HTTP `flatpak` is using, but I guess the highest possible (1.1 or 2), so that shouldn't be a problem.

I didn't think of hosting the repository on a GitHub page but that's a good idea, we don't even have to hook into the OpenRCT2 build system. I will give it a try, even if I'm more experienced in GitLab pages and CI (in fact I might try on GitLab, in the end it doesn't change anything).

**Comment by rmnvgr** [comment]
Okay, I think I have something.

Can you try [this flatpakref](https://gitlab.com/rmnvgr/openrct2-nightly-flatpaks/-/raw/master/io.openrct2.OpenRCT2.flatpakref?inline=false) and tell me if that works on your side?

The CI should rebuild the repo every night, so hopefully tomorrow there should be an update.

**Comment by takluyver** [comment]
It appears to download and launch OK :+1:

**Comment by janisozaur** [comment]
Hey, just chiming in - yes, `develop` is recommended for a few use cases, one of those is multiplayer. The other is when a community or some member would request a feature that we end up developing. This happens e.g. during contests or when we ask people to playtest stuff relating to the new save format. Finally, we get nearly-live bug reports courtesy of https://backtrace.io, which we try fixing quickly.

In the first use case nightlies are not good enough, they could end up being stuck always out of sync with what servers use, but should be fine for other use cases. I would still take nightlies if there are issues getting it done CI-style.

Do note https://openrct2.org is **not** our official website, but a friendly one.

I also realise many of those problems are due to the long periods between the releases. This one is on us, as this is fairly laborious  process (see https://gist.github.com/janisozaur/693b70c5d2c583d6c6f0e7ffbc983720) and our tests don't cover enough code, so there's occasionally need for bugfix release (https://www.reddit.com/r/rct/comments/g33ene/openrct2_v026_released/). Improving those areas would allow us to have more frequent releases and recommend those instead.

**Comment by rmnvgr** [comment]
Hey @janisozaur, thank you for the insight!

So if the development builds are not nightly builds, how often are they built? For each commit on the `develop` branch?

For now, the script on my test repo is called on a schedule, but it can be triggered at any time. However, as it is hosted on GitLab, at some point it might hit the platform limitations (hosting space and CI running time). How are regular development builds hosted and built? Is the build integrated in the OpenRCT2 CI or is it triggered somewhere else?

**Comment by janisozaur** [comment]
> For each commit on the develop branch?

Pretty much. Actually: for every push, but that's a technicality.

> How are regular development builds hosted and built?

https://github.com/OpenRCT2/OpenRCT2/blob/8d141faac26a4b5ee7c5af2e4cac3cdd99e75656/.github/workflows/ci.yml#L152

https://github.com/OpenRCT2/OpenRCT2/blob/8d141faac26a4b5ee7c5af2e4cac3cdd99e75656/scripts/upload-build#L84

**Comment by rmnvgr** [comment]
Thank you. So from what I understand, each build produces a single file that is uploaded to openrct2.org through an API. You said that it wasn't an official OpenRCT2 website, however I take you have control over it nonetheless?

Integrating the flatpak repo build in this might not be easy, I don't know what's the best way to do it:
- Build the flatpak repo in the OpenRCT2 CI and upload the files somewhere. But I think it needs the previous files to handle updates, although I need to verify it. And the host will have to decompress the files.
- Trigger the build from OpenRCT2 CI, build and host it on another machine. That could be done with my GitLab script now, but will need some additional programming if we want to host it somewhere else (mainly to respond to API calls).
- Investigate using [`flat-manager`](https://github.com/flatpak/flat-manager) even though it looks a bit overkill.

**Comment by janisozaur** [comment]
> I take you have control over it nonetheless

https://github.com/limetric/OpenRCT2.org
https://github.com/Limetric/OpenRCT2-binaries/releases

We also have some of our own infrastructure courtesy of https://digitalocean.com, that could potentially host it, but someone from the team would have to maintain it. We run a bunch of docker containers there already, adding another one would be the preferred way, especially if you could deliver one. How feasible would it be to have the files forming the flatpak be stored using S3?

**Comment by takluyver** [comment]
I think using S3 should be feasible - one of the main developers behind Flatpak apparently uses S3 for serving some repositories, or did a couple of years ago:

https://blogs.gnome.org/alexl/2017/02/10/maintaining-a-flatpak-repository/

**Comment by rmnvgr** [comment]
> We run a bunch of docker containers there already, adding another one would be the preferred way, especially if you could deliver one.
Yes, I can provide a Docker container. Does it only need to handle the repo building and file syncing to S3?

**Comment by takluyver** [comment]
It's probably easiest to build it on an existing CI service - it looks like OpenRCT2 is already using Github actions extensively, so it should be feasible to add it there. I think the question is just about how to host the repository.

**Comment by rmnvgr** [comment]
I don't know anything about S3, but is it possible to access the files externally?

Anyway, you can find on [my test repo](https://gitlab.com/rmnvgr/openrct2-nightly-flatpaks) the `Dockerfile` and the `build-flatpak-repo.sh` script used inside to build the flatpak repo and sync it to S3.

Another thought, for now I'm using the same app ID as the OpenRCT2 release, meaning that the user can only has the development or the release build. It might be interesting to change the ID to something like `io.openrct2.OpenRCT2-develop` so that it is possible to install both the release and development builds on the same system.

**Comment by takluyver** [comment]
Flatpak can handle having two versions of the same app ID installed side by side - I think you would refer to `io.openrct2.OpenRCT2//stable` or `io.openrct2.OpenRCT2//develop`. The suffix is referred to as a 'branch' - more details about the model here: https://docs.flatpak.org/en/latest/under-the-hood.html#git-for-apps

As I understand it, one version (by default the last one you installed) is the 'current' version, and the desktop files will launch that one. You can launch any installed version from the command line, and switch which is current (`flatpak make-current`).

**Comment by rmnvgr** [comment]
Yes you're right, right now I'm building in a `nightly` branch (I have to change that to `develop` though), and I can install both release and development flatpaks, and only the current one is visible. What I meant is, is it desirable to bypass this behaviour to show both builds in the DE or stick to flatpak's intended mechanisms?

**Comment by takluyver** [comment]
If you're going to bypass it, you probably want to change the names in the desktop files - something like "OpenRCT2 (development)" - otherwise you'll see 2 identifcal launchers with no easy way to distinguish them.

I'd be inclined to try using the Flatpak branches mechanism first, but I can see the case for the other way too.

**Comment by rmnvgr** [comment]
> If you're going to bypass it, you probably want to change the names in the desktop files - something like "OpenRCT2 (development)" - otherwise you'll see 2 identifcal launchers with no easy way to distinguish them.

I'm already doing that with `desktop-file-name-suffix` in the manifest :)

> I'd be inclined to try using the Flatpak branches mechanism first, but I can see the case for the other way too.

Okay. I believe this shares the files between the two flatpaks, so the user doesn't have to setup his game again, but it might make switching from the `develop` to the release branch hard if some incompatibilities are introduced.

**Comment by barthalion** [comment]
I just stumbled upon https://github.com/flathub/net.veloren.veloren/blob/master/.github/workflows/auto-update.yml. Might be useful for providing nightly builds to Flathub Beta.

**Comment by rmnvgr** [comment]
Thank you @barthalion for this link.

So if we were to distribute `develop` builds through Flathub Beta, the following will need to be done:
- From the OpenRCT2 workflow, [send a dispatch event](https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event) (either with `curl` or a [dispatch action](https://github.com/peter-evans/repository-dispatch)), on each push to the `develop` branch, to the OpenRCT2 flathub repository, containing the latest commit.
- On the OpenRCT2 flathub repository, respond to the [`repository_dispatch` event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch) by cloning the `beta` branch, replacing the source commit from the manifest with the one from the event, and pushing back so that the Flathub CI can build the `develop` flatpak and distribute it to users.

I'm not experienced in GitHub CI though, so I might try to write something, but it may take some time.

**Comment by rmnvgr** [comment]
Now that #5 and https://github.com/OpenRCT2/OpenRCT2/pull/12836 are merged, development builds are provided on the beta channel!

**Comment by takluyver** [comment]
Nice work :-)

**Comment by barthalion** [comment]
Indeed! My primary concern is how often the builds are going to happen. It would be nice to have some rate limit, even if it means not all commits will be build. We'll probably fine for OpenRCT2 itself but Flathub wasn't really built for this.

**Comment by rmnvgr** [comment]
@barthalion I've been thinking about it, and I think that if it becomes necessary, it can be quite easy to implement.

The necessary changes would be:

- When we receive the `repository_dispatch` event from upstream, commit the commit to another branch (`develop` for instance).
- Every day, or less frequently if necessary, run a GitHub job to merge the `develop` branch into `beta`, triggering the build.
