### ISSUE TITLE
update freedesktop runtime to 20.08

### ISSUE THREAD

**Issue by eszlari** [flathub/io.openrct2.OpenRCT2#9]

**Comment by takluyver** [comment]
Feel free to make a PR - Flathub automatically builds PRs and gives you instructions on how to test the change on your system.

**Comment by eszlari** [comment]
I know, I maintain several apps here on Flathub. This was just meant as a reminder.

**Comment by rmnvgr** [comment]
After eb32017a964285e5478d441e6026884d274c851b, beta builds now use the 20.08 Freedesktop runtime. I'll update the stable manifest on the next OpenRCT2 release.
